.github/workflows/run_tests.yml, pyproject.toml, setup.py
Small step towards resolving deprecation warnings during buildtime. (Lots more to do, but I think breaking down into individual PRs is a lot easier to track).
In particular, there are alot of python 2 legacy hacks still lingering around, we should clean them up eventually.
---
`distutils`  has been deprecated since python 3.10 (https://peps.python.org/pep-0632/). This PR replaces the distutils functions with their respective substitutes in `sysconfig` and `packaging` packages.
---
=> chore: deprecate distutils

tests/explainers/test_deep.py, tests/explainers/test_gradient.py
As mentioned in #15, this PR uses the tensorflow v1 compatible optimizers and fixes 3 tests with that change.
=> Use legacy tensorflow optimizers to stay compatible to tf v1.

tests/explainers/test_deep.py
Replaces the use of the Boston dataset in some Torch unit tests. These tests don't seem to rely on any particular feature of the dataset used, so switching the dataset should be safe.
Should help fix the test suite as per #4. Does not address the use of the Boston dataset in SHAP examples, as per #8.
=> Replace boston dataset in Torch unit tests

shap/datasets.py, tests/maskers/test_custom.py, tests/maskers/test_tabular.py, tests/plots/test_force.py
There are a few remaining usages of the boston dataset in the tests that are not covered by #19.
As the california dataset is much bigger (20k samples) than the boston dataset (500 samples), I only used 500 samples of the california dataset to not increase test runtime too much (same as slundberg#2501).
Related to #4 and #8
=> Remove remaining usages of the boston dataset.

README.md
Following the discussion https://github.com/dsgibbons/shap/discussions/1#discussioncomment-5789209 , I've taken a stab an some introductory text on the README, to help draw attention to the purpose of the fork.
I thought at this stage, it probably makes sense to put this information somewhere prominent, as a new CONTRIBUTING.md might not be noticed by people casually browsing the repo. For a title, how about "SHAP Community Fork"?
I haven't written a CONTRIBUTING.md in this PR, so that could be useful to have to flesh out the details of the how the pool of maintainers is managed.
=> Add introduction to fork on README

tests/explainers/test_deep.py
This PR attempts to fix some failing unit tests, supporting #4.
```
tests/explainers/test_deep.py::test_pytorch_custom_nested_models
tests/explainers/test_deep.py::test_pytorch_single_output
tests/explainers/test_deep.py::test_pytorch_multiple_inputs
```
These tests were previously failing as the boston house price dataset is no longer availble in sklearn. I made a previous PR #19 to replace the Boston house dataset with the California dataset; however, this inadvertently broke the pytorch models and the tests still fail.
This PR reverts these tests to use the original data, using the sklearn's recommended way of loading the boston dataset from the original source. The above tests now pass locally.
In future the tests could be written with a different dataset, but I think a first priority …
=> Fix pytorch tests

.gitignore
I like to use `venv` for development, but I don't want to accidentally commit environment paths to the repo. I've added all environment-related paths from [https://github.com/github/gitignore/blob/main/Python.gitignore](https://github.com/github/gitignore/blob/main/Python.gitignore). 
Ideally, I'd like to add most of the suggestions from the above link and to organise the `.gitignore` into sections. At this stage, I don't want to accidentally ignore anything that we depend on.
=> chore: add environment related paths to .gitignore

shap/explainers/_kernel.py
=> fix: deprecation warning in sklearn.linear_model.LassoLarsIC #2528

pyproject.toml, shap/explainers/_additive.py, shap/explainers/_exact.py, shap/plots/_force_matplotlib.py
Supports #21, incrementally getting more rules to pass.
=> Fix ruff rule F632: comparison of literals

shap/datasets.py
The `deprecated` decorator introduced in #20 should be called, otherwise right now it causes an error.
=> fix: deprecated should be called

.github/workflows/run_tests.yml, pyproject.toml, setup.py
<s>Might be tangentially related to #30.</s>
Related to the Original PR slundberg#1802, though that proposed change was indirectly introduced in slundberg#2017 (merged) already.
Related to the PR slundberg#2655, though the PR here takes a slightly different approach. Still using `oldest-supported-numpy` instead of hardcoding the minimum numpy version, and move away from `setup_requires` (see below).
* In the `run_tests.yml` github workflow, use `pip install -e` instead of `python setup.py develop` to perform an editable installation (trigger the `build` process).
* By taking advantage of [PEP 517](https://peps.python.org/pep-0517/), we can directly specify build dependencies in `pyproject.toml` instead of the _hacky_ method of monkey patching `cmdclass`. `setup_requires=` in the `setup` …
=> chore: deprecate setup.py develop

shap/utils/_general.py, tests/utils/test_general.py
cf. slundberg#2738
---
`shap.utils.sample()` is primarily used in our `datasets` module and notebooks to generate a subset of the original data. E.g. [here](https://github.com/dsgibbons/shap/blob/e24b7019cda8889376b72353f6ad8bdcb1db0bcc/shap/datasets.py#L47).
However, the current implementation uses [`sklearn`'s resample](https://github.com/scikit-learn/scikit-learn/blob/72a604975102b2d93082385d7a5a7033886cc825/sklearn/utils/__init__.py#L476) which uses `replace=True` by default.
I think this is unexpected / unwanted behaviour. This PR changes to using sklearn `shuffle()` instead of `resample()` which is just the same as setting `replace=False`.
* add tests for `shap.utils.sample`
* use `len()` in cases where there is no `.shape` attribute, e.g. for ordinary python lists.
=> fix: change sampling to without replacement

tests/plots/conftest.py
Minor fix to address some warnings in the test suite: close all matploblib images after test excution, to free up memory
=> Chore: Close matplotlib plots after use

.github/workflows/run_tests.yml, setup.py
Resolves #30  by adding tensorflow to the `test` optional dependency.
---
That said, I'm not entirely happy with this solution either. But it's a broader issue I want to bring up: which is that because of the way that we're running the tests and installing the test dependencies, we are testing in an environment that adheres to all of the requirements of ALL of the optional dependencies.
In the case of #30 , it's problematic because: `shap` should support numpy 1.24 (and indeed does, we merged PRs to remove deprecation warnings for that very purpose).
Yet because of tensorflow (an optional dependency), we are forced to test in an environment with numpy 1.23.5. I.e., we might miss bugs that only appear in the higher package versions.
Anyway, this is somewhat outside the scope of this PR, …
=> chore: add tensorflow to tests optional dependencies

MANIFEST.in, setup.py
Resolves #50.
* Remove the checks for optional dependencies in the recursive setup calls. I don't think we want the `setup()` to continue if any of the test optional dependencies fail to install. Also the previous logic was very brittle/inaccurate and cause issues like #50. 
* Remove `MANIFEST.in` file, it's not necessary because 1) the file path specified in the MANIFEST doesn't even exist, and 2) the package data is specified already in setup(). You can verify this by running pip install, and `tree_shap.h` is included in the wheel even without the MANIFEST.
=> fix: recursive depth limit in setup call

shap/plots/_waterfall.py
This allows for cases where the type of `features[order[i]]` is incompatible with string addition, e.g. boolean type.
=> [BUGFIX] yticklabels in `plots.waterfall()`

.gitattributes, CHANGELOG.md, README.md
=> Add a changelog

shap/explainers/_exact.py, shap/maskers/_image.py, shap/maskers/_tabular.py, shap/utils/_clustering.py, shap/utils/_masked_model.py
Fixes: https://github.com/slundberg/shap/issues/2909
This updates the Just-In-Time compiler decorators to explicitly avoid using "nopython" mode. Numba has recently been raising a DeprecationWarning as per:
https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit
This change replaces `@numba.jit` with `@numba.njit`, which is equivalent to `@numba.jit(nopython=True)`. This removes the deprecationwarning, but will explicitly cause an exception to be raised if the relevant functions cannot be jit-compiled without reverting to the slower "nopython" mode. So, might want to wait until the test suite is passing to ensure this change does not break anything.
=> Fix NumbaDeprecationWarning: specify nopython mode when using @jit

tests/explainers/test_linear.py
Resolves #64. See https://github.com/dsgibbons/shap/pull/61/files#diff-aaac45c56f18d99426abc36ac5c74ec085677e8349ebd0a23abdfa5f66bb4377 for further details.
Replace `shap.maskers.Image` with `shap.maskers.Fixed` as `Fixed` does not require non-essential dependencies like `cv2`.
=> tests: remove cv2 dependence for testing wrong masker #64

.github/workflows/run_tests.yml, setup.py, tests/explainers/test_linear.py
Closes #46
Defines two dependency groups, `test-core` and `test-extras`. The group `tests` remains as the union of both.
Adds an extra CI job to run tests with core dependencies only.
=> Separate out tests of optional dependencies, add new unit test job

.github/workflows/run_tests.yml, pyproject.toml
A very small bugbear change, to simplify the output of pytest when tests are run locally.
Configures pytest so that code coverage is not shown by default, but remains visible on the appropriate CI jobs.
=> Chore: Simplify pytest code coverage config

tests/plots/test_waterfall.py
waterfall plot test on py3.7 was failing. due to some very minor differences in text placement. No idea why but I don't think it's worth the time to investigate.
The "error" is not obvious and both plots look fine without scrutiny.
This PR increased the tolerance from 2 -> 3, which is still strict but passes the test.
Follow up PR from #62 .
=> accept minor variations in py3.7 waterfall plot

shap/explainers/_exact.py
This fixes a rather subtle bug that was inadvertently introduced by #27.
Related: #4
There is a check whether the variable `interactions` is equal to `1`. Currently, this statment also passes if `interactions` is equal to `True`, but this is unintentional. It's a rather nuanced as a `bool` is a subclass of an `int`, so `isinstance(interactions, int)` is not enough. 
Side fun fact: this comparison was previously achieved with `interactions is 1`, which is not safe but _may_ work some of the time depending on the python implmentation. Here's a fun python phenomenon:
```
>>> a = 1
>>> b = 1
>>> a is b
True
>>> a = 99999999
>>> b = 99999999
>>> a is b
False
```
=> Fix failing test from incorrect comparison of bools and ints

shap/explainers/_exact.py, shap/explainers/_partition.py, shap/links.py, shap/maskers/_image.py, shap/maskers/_tabular.py, shap/utils/_clustering.py, shap/utils/_masked_model.py
Original issue: https://github.com/slundberg/shap/issues/2909
PR #9 attempted to solve the issue by explicitly specifying `nopython=False`, but inadvertently introduced other Deprecation warnings as `nopython` mode is being removed entirely.
The recommendation from numba is to disable the object mode behaviour, by setting `nopython=True` or equivalently using `njit`.
=> Fix further NumbaDeprecationWarnings: migrate from jit to njit

.github/workflows/run_tests.yml
Minor change that should make it easier to review test results that relate to pytest-mpl failures, without having to re-run tests locally.
=> Chore: Upload pytest-mpl failures as artifacts

.github/workflows/run_tests.yml, setup.py
Closes #71 
This may require a fair bit of work before this is ready, for example fixing various deprecations from other libraries. We could continually rebase this branch on top of master to see how the test suite runs on 3.11.
=> Add support for python 3.11

.github/workflows/run_tests.yml
Just a small optimization
- not to waste resources running tests in PR when no source code is changed. E.g. if `CHANGELOG.md` or the Jupyter notebooks are updated. I still propose to always run tests when pushing to `master`.
- Make concurrency cancel-in-progress, which is to cancel running jobs if another push to the same ref was made in the meantime. See an example with this PR, the previous workflow was automatically canceled when another push was made to the same `ci/specify-paths` branch.
=> ci: only run tests when src code changes

README.md
Just updating the badges to show that tests are passing, and to point users to the new documentation page.
Removed the badges pointing back to `slundberg/shap` repo.
Related to #83 .
=> chore: add shap-community badges to README

shap/_explanation.py, tests/test_explanation.py
Part of #54.
1. `Explanation.hstack` method was using a non-existent variable "axis" (probably copied from the other helper methods like `sum`). The implementation as it is didn't make any sense, so I modified it to what I think made the most sense, which is to hstack the inner arrays and return a new Explanation object.
2. Added tests for hstack only.
=> fix: Explanation hstack undefined name error

README.md, docs/index.rst
Add installation instructions to `README.md` and clear up confusion around PyPI/conda. See #78 and #80.
=> chore: add installation instructions #78 #80

pyproject.toml, shap/plots/_beeswarm.py, shap/plots/_utils.py
Related to Issue #21, and is a continuation of PR #25 when ruff was initially introduced to the project.
**Dependencies**: PR #53 (deprecating MimicExplainer) must be merged in first, because that's one of the main offenders of F821. ✅
---
The changes are quite major considering it involves mostly dead / unreachable code. Requesting a thorough review, but any review (even partial!) would be appreciated. I'll leave review comments in the relevant places later on to make code review a little easier for you guys, but here's the tl;dr:
1. <s>`Explanation.hstack` method was using a non-existent variable "axis" (probably copied from the other helper methods like `sum`). The implementation as it is didn't make any sense, so I modified it to what I think made the most sense, which is to hstack …
=> fix: ruff rule F821 (undefined name)

shap/plots/_utils.py, tests/plots/test_utils.py
Following on from #54, this PR provides fixes for future `ruff` rules BLE001 (blanket exception catching) and S110 (try-except-pass). This PR also provides a test case to illustrate the purpose of `convert_color`. This test is probably a bit redundant, but good for extending coverage at least.
=> chore: make convert_color ruff compliant and add test

CHANGELOG.md, shap/explainers/_tree.py, tests/explainers/test_tree.py
The commits can be reviewed individually. In short,
1. Refactor `lightgbm` tests into a TestClass to separate them from the xgboost, catboost etc. tests.
2. Pass X directly into the `.shap_values()` function call (without first converting to numpy array).
3. Add a test to make sure we don't introduce regression accidentally in the future.
Resolves #66 (read the issue for a background).
Related to issue slundberg#2144 (the original issue), and port of PR slundberg#2166 (but I implemented in a different way).
=> fix: lightgbm call with categoricals bug

pyproject.toml, shap/_explanation.py, shap/explainers/_sampling.py, shap/plots/_bar.py, shap/plots/_beeswarm.py, shap/plots/_image.py, shap/plots/_scatter.py, shap/plots/_text.py, shap/plots/_violin.py, shap/plots/_waterfall.py, shap/utils/_general.py
Related to Issue https://github.com/dsgibbons/shap/issues/21, and is a continuation of PR https://github.com/dsgibbons/shap/pull/25 when ruff was initially introduced to the project.
This PR aims to make the codebase F841-compliant ("Local variables assigned but unused").
For the variables with no clear purpose, I removed them. Some I chose to keep/comment away (somewhat arbitrary decision based on a feeling that it might be useful for future reference, feel free to tell me to delete them).
**Dependencies**: The `hstack` bug of Explanation makes an appearance here too. So PR #86 should be merged in first. ✅ **DONE**
=> fix: ruff rule F841 (unused variable)

.github/workflows/run_tests.yml
Supports #42.
Adds caching of pip dependencies for faster CI times. Reduces time to install dependencies from ~4min30 to ~3mins. See [discussion on #42](https://github.com/dsgibbons/shap/issues/42#issuecomment-1571735472) for measured timings for alternative ideas, and discussion of total cache limits.
=> Cache pip dependencies on CI

.github/workflows/codeql-analysis.yml
This PR aims to get the CodeQL check running and passing. The upstream slundberg repo has CodeQL scanning enabled, and the CPP check currently fails. 
EDIT: updated to fix build dependency, and keep `cpp` check.
=> Fix failing C++ CodeQL checks

tests/explainers/test_deep.py, tests/explainers/test_gradient.py
Fixes some warnings in the test suite by ensuring the `InteractiveSession` is closed.
The test could be rewritted to use a regular `Session` and perhaps a `with` statement, but this is a minimal change to fix the warning.
=> Chore: fix test suite warnings by closing tensorflow session

CHANGELOG.md, README.md, docs/index.rst
This branch aims to get this fork ready for merging into the main repo, by reverting any fork-specific changes such as the change to the README. I will continually rebase this branch on top of `dsgibbons/master`.
Pending ongoing discussion on https://github.com/slundberg/shap/discussions/2942
=> Prepare for fork merge: revert changes specific to SHAP Community Fork
